version: 2.1

jobs:
  build:
    docker:
      - image: "ubuntu:focal"

    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      
      - run:
          name: Installing GCC and BUILDING-ESSENTIAL
          command: 'apt-get update && apt-get install -y gcc g++ build-essential'
     
      - run:
          name: Installing WGET and TAR
          command: 'apt-get update && apt-get install -y wget tar'

      - run:
          name: Install CMAKE
          #command: 'apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get install -y cmake'
          command: 'cd /tmp  &&  wget https://github.com/Kitware/CMake/releases/download/v3.20.0/cmake-3.20.0.tar.gz  &&  tar -xzvf cmake-3.20.0.tar.gz       && cd cmake-3.20.0   &&  ./bootstrap   &&  make -j4  && make install'

      - run:
          name: Creating Build Files
          command: 'cmake .'
      
      - run:
          name: Point Unit Testing
          command: 'ctest'
