version: 2.1

jobs:
  build:
    docker:
      - image: "ubuntu:focal"

    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      
      - run:
          name: Install CMAKE
          command: 'apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get install -y cmake'
      
      - run:
          name: Creating Build Files
          command: 'cmake .'
      
      - run:
          name: Point Unit Testing
          command: 'ctest'
